on:
   push:
     branches:
       - master
   pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.6
          - ruby: 2.7
          - ruby: 3
    runs-on: ubuntu-latest
    name: RSpec suite with Ruby ${{ matrix.ruby }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      EARTHLY_RUBY_VERSION: ${{ matrix.ruby }}
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: "0.6.30"
    - uses: actions/checkout@v3
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Earthly version
      run: earthly --version
    - name: Run Rubocop
      run: earthly --ci --allow-privileged +rubocop --EARTHLY_RUBY_VERSION=$EARTHLY_RUBY_VERSION
    - name: Run Rspec
      run: earthly --ci --allow-privileged +rspec --EARTHLY_RUBY_VERSION=$EARTHLY_RUBY_VERSION
